@startuml

class Client{
}
interface Target {
	+ targetMethod1 : ??
	+ targetMethod2 : ??
}
class Adaptor{
	+ target : Target
	+ adaptee: Adaptee

	+ targetMethod1() : ??
	+ targetMethod2() : ??
}
class Adaptee{
	+ methodA() : ??
	+ methodB() : ??
	+ methodC() : ??
}

Client --> Target : uses
Target <|. Adaptor : implements
Adaptor -|> Adaptee : extends

@enduml