@startuml

class Client{
	+adaptor : Adaptor

	+doWork()
}
interface Adaptor{
	+ methodA() : ??
}
class AdaptorNImpl{
	- adaptee: AdapteeN

	+ methodA() : ??
}
class Adaptee1{
	+ method1() : ??
}
class Adaptee2{
	+ method2() : ??
}
class Adaptee3{
	+ method3() : ??
}
class AdapteeN{
	+ methodN() : ??
}

Client --> Adaptor : uses
Adaptor <|- AdaptorNImpl : implements
AdaptorNImpl o--> Adaptee1 : has
AdaptorNImpl o--> Adaptee2 : has
AdaptorNImpl o--> Adaptee3 : has
AdaptorNImpl o--> AdapteeN : has

@enduml